[package]
name = "refcomp"
version = "0.1.0"
authors = ["Jad Ghalayini <jad.ghalayini@hotmail.com>"]
edition = "2018"

[dependencies]
pest = "^2.1.0"
pest_derive = "^2.1.0"
lazy_static = "^1.2.0"
by_address = "^1.0.4"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm7-0" }
